export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string;
  price: number;
  priceExGst: number;
  inStock: boolean;
  reviews: number;
  shortDescription?: string;
  features: string[];
  specs: Record<string, string>;
  images: string[];
  manualUrl?: string;
  isFlagship?: boolean;
  compatibility?: string[];
}

export const CATEGORIES = [
  "Analog Audio Remote Kits",
  "Digital Audio Remote Kits",
  "Digital Audio Decoders",
  "Others",
];

export const PRODUCTS: Product[] = [
  {
    id: "ft004d-usb-bt",
    sku: "FT004D-USB+BT-EXSO",
    name: "FT004D-USB+BT (Small Display)",
    category: "Analog Audio Remote Kits",
    price: 2499.00,
    priceExGst: 2117.80,
    inStock: false,
    reviews: 0,
    shortDescription: "5.1CH Remote Kit (Exso Bass) with small display.",
    features: [
      "6-ch independent electronic volume (0 to –99dB, 1dB step, –∞dB)",
      "6-ch independent gain (0–+14dB, 2dB step)",
      "Bass/Treble ±14dB (2dB step)",
      "1×6Ch DVD input, 3×2Ch stereo inputs",
      "Built-in subwoofer crossover and L-R matrix surround",
      "3-slot memory (MOD1–3)",
      "Full-function digital rotary encoder",
      "User-changeable source names, welcome display, key mapping",
      "FT003 remote source sync option",
      "USB Audio: 16-bit DAC; MP3/WAV/FLAC/WMA; scrolling file/folder name display",
      "Bluetooth v4.0, A2DP low-latency, MP3/AAC/SBC",
      "Voice-over speaker test tone",
    ],
    specs: {
      "Power Supply": "12–15 VDC single supply, 1A min",
      "Preamp Dimensions": "60×135mm",
      "Display Dimensions": "43×101mm",
      "Included": "FT004D display kit, RAD001 Exso Bass preamp kit, RMC cables, encoder, USB socket, FTB011 remote",
    },
    images: ["https://picsum.photos/seed/ft004d/800/800", "https://picsum.photos/seed/ft004d-2/800/800"],
  },
  {
    id: "ft004g-max-usb-bt",
    sku: "FT004G-MAX-USB+BT-EXSO",
    name: "FT004G-MAX-USB+BT (Big Display)",
    category: "Analog Audio Remote Kits",
    price: 3500.00,
    priceExGst: 2966.10,
    inStock: true,
    reviews: 0,
    isFlagship: true,
    shortDescription: "Total Audio Control with High-Resolution USB Audio and Bluetooth 5.4.",
    features: [
      "High-Resolution USB Audio (MP3/FLAC/AAC/WMA/APE/WAV)",
      "Bluetooth 5.4 with AAC/SBC",
      "Smart Audio Display (codec, song title, artist, album, progress, status)",
      "Premium Sound Quality with Built-in Speaker Test",
      "FTLink Mobile App for remote configuration, playback control, firmware updates",
      "Modern User Interface",
      "Universal Plug & Play (auto-detects FT003 mini decoders)",
    ],
    specs: {
      "Included": "Total Audio Control board, Big Display, FTLink Mobile App",
    },
    images: ["https://picsum.photos/seed/ft004g/800/800", "https://picsum.photos/seed/ft004g-2/800/800", "https://picsum.photos/seed/ft004g-3/800/800"],
    compatibility: ["FT003 Mini Decoders"],
  },
  {
    id: "ft006-v2",
    sku: "FT006-V2",
    name: "FT006 5.1Ch Remote Kit V2",
    category: "Analog Audio Remote Kits",
    price: 1899.00,
    priceExGst: 1609.32,
    inStock: true,
    reviews: 2,
    shortDescription: "5.1Ch Remote electronic volume control kit for assembled home theatre.",
    features: [
      "Same volume/gain/tone control family as FT004D",
      "1×6Ch DVD input, 3×2Ch stereo",
      "Subwoofer crossover and L-R matrix surround",
      "MP3/MP5/board remote sync",
      "FT003 mini decoder & Rush optical board sync",
      "User-programmable IR sync",
      "User-programmable welcome name",
    ],
    specs: {
      "Power Supply": "12–15 VDC single supply",
      "Included": "7-pin RMC connectors ×3, 2-pin RMC connector ×1, rotary encoder, FT017 remote control ×1",
    },
    images: ["https://picsum.photos/seed/ft006/800/800"],
    manualUrl: "/files/pdf/FT006-V2-Manual.pdf",
    compatibility: ["FT003 mini decoder", "Rush optical board"],
  },
  {
    id: "ft008-v4-opt-cox",
    sku: "FT008-V4",
    name: "FT008-V4 DSP Kit (Optical/Coax)",
    category: "Digital Audio Remote Kits",
    price: 7499.00,
    priceExGst: 6355.08,
    inStock: false,
    reviews: 1,
    isFlagship: true,
    shortDescription: "5.1Ch (DOLBY/DTS) DSP Kit with Optical and Coaxial inputs.",
    features: [
      "Decoders: 24-bit DTS/DOLBY/Prologic II",
      "Prologic II modes: Movie, Music, Matrix, Virtual, Emulation",
      "2 volume-control modes; 50dB individual volume; 15dB trim volume",
      "5.1 voice-over/pink-noise test tone",
      "Auto gain control; bass/treble tone control",
      "USB (MP3/WAV/WMA/FLAC/APE)",
      "Bluetooth v4.2 (SBC, AAC)",
      "Prologic II via Bluetooth/USB/AUX",
      "Advanced settings: DSP speaker config, crossover HPF/LPF, bass management, audio delay",
    ],
    specs: {
      "Inputs": "2× Optical (S/PDIF), 2× Coaxial (S/PDIF), 2× Stereo Analogue (AUX)",
      "DSP": "Cirrus Logic CS493292-CLZ",
      "DAC/ADC": "24-bit DAC = GC4344, DIR = GC8416, 24-bit ADC = GC5388",
      "Volume Control IC": "R2S15902FP",
      "Output Opamp": "NE5532",
      "MCU": "JL 32-bit RISC CPU, STC8F2K64S2 8-bit",
      "PSU regulator": "LM2596-5V",
    },
    images: ["https://picsum.photos/seed/ft008-opt/800/800", "https://picsum.photos/seed/ft008-opt-2/800/800"],
    compatibility: ["FT010H-V2 HDMI Module"],
  },
  {
    id: "ft008-v4-hdmi",
    sku: "FT008-V4-HDMI",
    name: "FT008-V4 HDMI DSP Kit",
    category: "Digital Audio Remote Kits",
    price: 11499.00,
    priceExGst: 9744.92,
    inStock: false,
    reviews: 2,
    isFlagship: true,
    shortDescription: "5.1Ch (DOLBY/DTS) DSP Kit with 3× HDMI inputs and ARC.",
    features: [
      "Decoders: 24-bit DTS/DOLBY/Prologic II",
      "3× HDMI Input / 1× Output with ARC",
      "Prologic II modes: Movie, Music, Matrix, Virtual, Emulation",
      "2 volume-control modes; 50dB individual volume; 15dB trim volume",
      "5.1 voice-over/pink-noise test tone",
      "Auto gain control; bass/treble tone control",
      "USB (MP3/WAV/WMA/FLAC/APE)",
      "Bluetooth v4.2 (SBC, AAC)",
      "Advanced settings: DSP speaker config, crossover HPF/LPF, bass management, audio delay",
    ],
    specs: {
      "Inputs": "3× HDMI In, 1× HDMI Out (ARC), 2× Optical, 2× Coaxial, 2× AUX",
      "DSP": "Cirrus Logic CS493292-CLZ",
      "DAC/ADC": "24-bit DAC = GC4344, DIR = GC8416, 24-bit ADC = GC5388",
      "Volume Control IC": "R2S15902FP",
      "Output Opamp": "NE5532",
    },
    images: ["https://picsum.photos/seed/ft008-hdmi/800/800", "https://picsum.photos/seed/ft008-hdmi-2/800/800"],
  },
  {
    id: "ft003-v2",
    sku: "FT003-V2",
    name: "FT003-V2 Mini Decoder",
    category: "Digital Audio Decoders",
    price: 2899.00,
    priceExGst: 2456.78,
    inStock: false,
    reviews: 6,
    shortDescription: "5.1Ch HDMI ARC/OPT/COX DTS/DOLBY Mini Decoder.",
    features: [
      "5.1 Dolby/DTS/Dolby Pro Logic II",
      "Pro Logic II modes (Movie/Music/Matrix/Virtual/Emulation)",
      "Futech-original modes (Futech Surround, Multichannel Stereo, 2.1 Channel)",
      "24-bit DAC/ADC",
      "Inbuilt bass management",
      "Full LED status",
      "80Hz crossover (HPF/LPF)",
    ],
    specs: {
      "Connectivity": "Optical, Coaxial, TV (HDMI ARC), AUX",
      "Power Supply": "8–24 VDC single supply, 1A min",
      "Dimensions": "76×60mm",
      "Included": "7-pin RMC connector wire, 2-pin RMC connector wire, durable metal back panel",
    },
    images: ["https://picsum.photos/seed/ft003/800/800", "https://picsum.photos/seed/ft003-2/800/800"],
    manualUrl: "/files/pdf/FT003/FT003 Manual V2.pdf",
    compatibility: ["Analog Audio Remote Kits", "FT004G-MAX-USB+BT"],
  },
  {
    id: "ft003-v2-box",
    sku: "FT003-V2-BOX",
    name: "FT003-V2 Mini Decoder with BOX",
    category: "Digital Audio Decoders",
    price: 3499.00,
    priceExGst: 2965.25,
    inStock: false,
    reviews: 1,
    shortDescription: "5.1Ch HDMI ARC/OPT/COX DTS/DOLBY Mini Decoder enclosed in a box with accessories.",
    features: [
      "5.1 Dolby/DTS/Dolby Pro Logic II",
      "Pro Logic II modes and Futech-original modes",
      "24-bit DAC/ADC and Inbuilt bass management",
      "Full LED status and 80Hz crossover",
    ],
    specs: {
      "Connectivity": "Optical, Coaxial, TV (HDMI ARC), AUX",
      "Power Supply": "12V single supply, 1A min",
      "Dimensions": "76×60mm",
      "Included": "Mini Decoder enclosed in BOX, HDMI cable ×1, 12V-1A power adapter ×1",
    },
    images: ["https://picsum.photos/seed/ft003-box/800/800"],
    manualUrl: "/files/pdf/FT003/FT003 Manual V2.pdf",
    compatibility: ["Analog Audio Remote Kits", "FT004G-MAX-USB+BT"],
  },
  {
    id: "ft010h-v2",
    sku: "FT010H-V2",
    name: "FT010H-V2 HDMI Plug-In Module",
    category: "Digital Audio Decoders",
    price: 3304.00,
    priceExGst: 2800.00,
    inStock: true,
    reviews: 0,
    shortDescription: "Plug-and-play upgrade HDMI module for FT008 DSP Kits.",
    features: [
      "HDMI 2.0b / HDMI 1.4 / DVI 1.0 support",
      "HDCP 2.3/2.2/1.4",
      "Up to 6Gbps; up to 4K×2K@60Hz",
      "Adaptive receiver equalization",
      "3D and HDR/HDR+ (Dolby Vision, HLG)",
      "8/10/12-bit color depth",
      "ARC support and auto active-source/ARC routing",
    ],
    specs: {
      "Compatibility": "FT008 v2/v3/v4 kits (firmware must be v2.4 minimum)",
      "Installation": "Plug-and-play upgrade module — no extra wiring needed",
    },
    images: ["https://picsum.photos/seed/ft010h/800/800"],
    compatibility: ["FT008-V4 DSP Kit (Optical/Coax)", "FT008 v2/v3/v4 kits"],
  },
];

export const BUSINESS_INFO = {
  name: "FUTECH AUDIOS AND INNOVATION",
  proprietor: "Sakthivel",
  address: "7/91C, Radhamani complex, AVP Rd, Avinasi Koundam, Angeripalayam, Tiruppur, Tamil Nadu 641603",
  phone: "8124412222",
  email: "sales@futechaudios.com",
  social: {
    facebook: "https://facebook.com/futechaudios",
    youtube: "https://youtube.com/futechaudios",
    whatsapp: "https://wa.me/message/7FCT24WOX25FE1",
  }
};
